# Generated by Django 5.0 on 2024-03-01 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=30)),
                ('Last_Name', models.CharField(max_length=30)),
                ('E_mails', models.CharField(max_length=50)),
                ('Contact_no', models.IntegerField(verbose_name=12)),
                ('Address', models.TextField()),
            ],
        ),
    ]
